import React from 'react';
import PageButtons from "./PageButtons"
import Head from "next/head"
import Link from 'next/link';
//import { useSession } from 'next-auth/react';
//import { api } from "../utils/api";

interface pagesType {
  [key: string]: {
    pagePath: string,
    label: string,
    style: string
  }
}
const pages: pagesType = {
  "Gallery": { pagePath: "/gallery", label: "GALLERY", style: "" },
  "Coaches": { pagePath: "/coaches", label: "COACHES", style: "" },
  "Schedules": { pagePath: "/schedule", label: "SCHEDULES", style: "" },
  "Classes": { pagePath: "/classes", label: "CLASSES", style: "" },
  "About": { pagePath: "/about", label: "ABOUT", style: "" },
}

const displayPages = () => {
  return Object.keys(pages).map((page, index) => {
    const style = pages[page]?.style
    return <PageButtons key={index} pagePath={pages[page]?.pagePath} label={pages[page]?.label} style={style} />
  })
}

const Header: React.FC = () => {
  //const { data: session } = useSession();
  //const user = session ? session.user : null

  return (
    <>
      <Head>
        <title>Velocity Gymnastics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="header-background">
        <div className="header-top">
          <Link className="header-logo" href="/">
            Velocity Gymnastics
          </Link>
          <div className="header-enroll">
            Enroll Now
          </div>
        </div>

        <div className="header-pages">
          {displayPages()}
          <div className="header-socials">
            <div className="social"> FB </div>
            <div className="social"> IG </div>
            <div className="social"> YT </div>
          </div>
        </div>

        <div className="header-bottom">

        </div>
      </div>
    </>
  );
};
export default Header;

